// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgyfnarygrltmnlqfurg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFneWZuYXJ5Z3JsdG1ubHFmdXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzI1NjYsImV4cCI6MjA2MjU0ODU2Nn0.Wt785_4sp-BqVwhD99TBXh5G04DwIsPzf_EeX8slY-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);